# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/3842c17c-535b-4197-9b8a-ddfdf4840e6c";
    fsType = "ext4";
  };

  fileSystems."/bin" = {
    device = "/usr/bin";
    fsType = "none";
    options = [ "bind" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/307D-9DAF";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/media/sda" = {
    device = "/dev/disk/by-uuid/e5257826-918c-4b94-a9b1-4fb0048a9685";
    fsType = "ext4";
  };

  fileSystems."/media/sdb" = {
    device = "/dev/disk/by-uuid/3c6d7424-0d41-4dbc-881d-6cb227b28cd6";
    fsType = "ext4";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/454a45ed-04df-442a-9bd6-c59d535b4a12"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
